Illumos 5960 zfs recv should prefetch indirect blocks Illumos 5925 zfs receive -o origin=
Reviewed by: Prakash Surya <prakash.surya@delphix.com>
Reviewed by: Matthew Ahrens <mahrens@delphix.com>

depends on #3574 Illumos 5745 zfs set allows only one dataset property to be set at a time
depends on #3611 Illumos 5746 more checksumming in zfs send

diverged code base from Illumos:

[lib/libzfs/libzfs_sendrecv.c]
b8864a233c569edcc57c686f3ea8cd1ae3b89153 Fix gcc cast warnings
325f023544bbec6a478882c442e15304ee379759 Add linux kernel device support
5c3f61eb498e8124858b1369096bf64b86a938e7 Increase Linux pipe buffer size on 'zfs receive'

[module/zfs/zfs_vnops.c]
3558fd73b5d863304102f6745c26e0b592aca60a Prototype/structure update for Linux
c12e3a594a49ed10b7870d950c1f336f78f136cb Restructure zfs_readdir() to fix regressions

[module/zfs/zvol.c]
function
@zvol_map_block(spa_t *spa, zilog_t *zilog, const blkptr_t *bp,
is non-existent in ZoL

[module/zfs/dmu.c]
in function
dmu_prefetch(objset_t *os, uint64_t object, uint64_t offset, uint64_t len)
int i
is initialized before the following code block (c90 vs. c99)

[module/zfs/Makefile.in + lib/libzpool/Makefile.am]
47a4a6fd5fa1f1f60bcf6af19e453ecf0292f7d1 Support parallel build trees (VPATH builds)

[module/zfs/dbuf.c]
fc5bb51f08a6c91ff9ad3559d0266eeeab0b1f61 Fix stack dbuf_hold_impl()
9b67f605601c77c814037613d8129562db642a29 Illumos 4757, 4913
{4757 ZFS embedded-data block pointers ("zero block compression") ,
 4913 zfs release should not be subject to space checks}
{reference} 34229a2f2ac07363f64ddd63e014964fff2f0671 Reduce stack usage for recursive traverse_visitbp()

[module/zfs/dmu_send.c]
b58986eebf3c47c946393da4b968ee33edaea99e Use large stacks when available
241b5415748859a3c272fc8f570f2368e93adde9 Illumos 5959 - clean up per-dataset feature count code
{reference} 77aef6f60ea29f6d3769addc778db6328ac85755 Use vmem_alloc() for nvlists
00b46022c676e402e3f33ce93ee2983bbad2c46f Add linux kernel memory support

[module/zfs/zvol.c]
9965059ab9991a5fc7df9a489021e73880b3bcc0 Prefetch start and end of volumes

[module/zfs/dmu_send.c, C90 warnings - previous commits, code thus less clear to read]
Illumos 5746 more checksumming in zfs send

[module/zfs/dbuf.c, ISO C90 - mixed declarations and code]
arc_flags_t aflags =
uint64_t nextblkid = dpa->dpa_zb.zb_blkid >>
dmu_buf_impl_t *db = dbuf_find(dn->dn_objset, dn->dn_object,
zio_t *pio = zio_root(dmu_objset_spa(dn->dn_objset), NULL, NULL,
blkptr_t *bp = ((blkptr_t *)abuf->b_data) +
dbuf_prefetch_arg_t *dpa = kmem_zalloc(sizeof (*dpa), KM_SLEEP);
dsl_dataset_t *ds = dn->dn_objset->os_dsl_dataset;

[module/zfs/dmu_send.c, ISO C90 - mixed declarations and code]
dnode_phys_t *blk = abuf->b_data;
uint64_t dnobj = zb->zb_blkid * (blksz >> DNODE_SHIFT);
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode: for (struct receive_ign_obj_node *n =
struct send_block_record *to_data;
struct receive_ign_obj_node *n;
struct receive_ign_obj_node *last_object;

FIXME: man/man8/zfs.8
FIXME: different manpage format, currently I don't "get it" yet

Ported-by: kernelOfTruth kerneloftruth@gmail.com